Pskov_Interactive/urls.py
"""
Definition of urls for Pskov_Interactive.
"""

from datetime import datetime
from django.urls import path, re_path
from django.contrib import admin
from django.contrib.auth.views import LoginView, LogoutView
from django.views.generic.edit import CreateView
from app import forms, views

from django.conf.urls.static import static
from django.contrib.staticfiles.urls import staticfiles_urlpatterns
from django.conf import settings

urlpatterns = [
    path('', views.home, name = 'home'),
    path('about/', views.about, name = 'about'),
    path('videos/', views.videos, name='videos'),
    path('auth/sign-in/',
         LoginView.as_view(
             template_name = 'app/pages/auth/sign-in.html',
             authentication_form = forms.SignInForm,
             extra_context = { 'year' : datetime.now().year, 'page': 'login', 'page_title': 'Вход' },
         ),
         name='sign-in'),
    path('auth/sign-up/', views.sign_up, name = 'sign-up'),
    path('auth/sign-out/', LogoutView.as_view(next_page='/auth/sign-in/'), name = 'sign-out'),
    path('profile/<int:id>/', views.profile, name='profile'),
    path('profile/', views.profile, name='profile'),
    path('news/', views.news, name='news'),
    path('news/<str:tag>/', views.news, name='news'),
    path('news/article/<int:id>', views.article, name='article'),
    path('news/comment/<int:id>', views.comment, name='comment'),
    path('store/', views.store, name='store'),
    path('accounts/profile/', views.redirect_home, name='redirect_home'),

    path('edit/profile/', views.edit_profile, name='edit_profile'),
    path('place/order/', views.order, name='order'),
    path('update/order/<int:id>', views.update_order_status, name='update_order'),

    path('manage/', views.manage, name='manage'),
    path('manage/games/', views.manage_games, name='manage_games'),
    path('manage/game/<int:id>', views.manage_game, name='manage_game'),
    path('manage/dlcs/', views.manage_dlcs, name='manage_dlcs'),
    path('manage/dlc/<int:id>', views.manage_dlc, name='manage_dlc'),
    path('manage/accessories/', views.manage_accessories, name='manage_accessories'),
    path('manage/accessory/<int:id>', views.manage_accessory, name='manage_accessory'),
    path('manage/news/', views.manage_news, name='manage_news'),
    path('manage/article/<int:id>', views.manage_article, name='manage_article'),
    path('manage/users/', views.manage_users, name='manage_users'),
    path('manage/user/<int:id>', views.manage_user, name='manage_user'),
    path('manage/orders/', views.manage_orders, name='manage_orders'),

    path('admin/', admin.site.urls, name='admin')
]

urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)
urlpatterns += staticfiles_urlpatterns()

urlpatterns += [ re_path('.*', views.missing_page, name='missing_page') ]

app/models.py
"""
Definition of models.
"""
from django.db import models
from django.contrib import admin
from django.urls import reverse
from django.contrib.auth.models import AbstractUser

from random import randint
from datetime import datetime


### shop ###

class Game (models.Model):
    name = models.CharField(
        max_length = 100,
        unique_for_date = "created",
        verbose_name = "Название игры"
    )

    abbreviation = models.CharField(
        max_length = 10,
        verbose_name = "Сокращение игры"
    )

    description = models.TextField(
        verbose_name = "Описание игры"
    )

    theatre = models.CharField(
        max_length = 100,
        verbose_name = "Место действия"
    )

    timeline = models.CharField(
        max_length = 100,
        verbose_name = "Время действия"
    )

    timeline_start = models.IntegerField(
        verbose_name = "Год начала действия"
    )

    timeline_end = models.IntegerField(
        verbose_name = "Год окончания действия"
    )

    tag = models.CharField(
        max_length = 20,
        verbose_name = "Тег игры"
    )

    colour = models.CharField(
        max_length = 7,
        verbose_name = "Цвет тега игры"
    )

    image = models.FileField(
        default = 'temp.jpg',
        verbose_name = 'Логотип игры'
    )

    status_choices = [
        ('not-started'       , 'Не начата'),
        ('planned'           , 'Запланирована'),
        ('closed-development', 'В закрытой разработке'),
        ('open-development'  , 'В открытой разработке'), ### here payments may take place
        ('beta-testing'      , 'Тестирование'),
        ('published'         , 'Опубликована'),
        ('not-supported'     , 'Не поддерживается'),
    ]

    status = models.CharField(
        max_length=20,
        choices = status_choices,
        default = 'not-started',
        verbose_name = "Статус игры"
    )

    price = models.IntegerField(
        default = 0,
        verbose_name = "Цена за копию игры"
    )

    created = models.DateTimeField(
        default = datetime.now(),
        db_index = True,
        verbose_name = "Дата создания"
    )

    published = models.DateTimeField(
        default = datetime.now(),
        db_index = True,
        verbose_name = "Дата публикации"
    )
    
    def __str__ (self): return self.name

    class Meta:
        db_table = "Games"
        ordering = [ "-published", "-created" ]
        verbose_name = "Игра"
        verbose_name_plural = "Игры"


class DLC (models.Model):
    name = models.CharField(
        max_length = 100,
        unique_for_date = "published",
        verbose_name = "Название дополнения"
    )

    about = models.ForeignKey(
        Game,
        on_delete=models.CASCADE,
        verbose_name='Для какой игры'
    )

    image = models.FileField(
        default='temp.jpg',
        verbose_name='Изображение'
    )

    content = models.TextField(
        verbose_name = "Полное содержание"
    )

    price = models.IntegerField(
        default = 0,
        verbose_name = "Цена за дополнение"
    )

    published = models.DateTimeField(
        default = datetime.now(),
        db_index = True,
        verbose_name = "Дата публикации"
    )
    
    def __str__ (self): return self.name + ' (DLC)'

    class Meta:
        db_table = "DLCs"
        ordering = [ "-published" ]
        verbose_name = "Дополнение"
        verbose_name_plural = "Дополнения"


class AccessoryTag (models.Model):
    tag = models.CharField(
        max_length = 20,
        verbose_name = "Тег товара"
    )

    colour = models.CharField(
        max_length = 7,
        verbose_name = "Цвет тега товара"
    )
    
    def __str__ (self): return '#' + self.tag

    class Meta:
        db_table = "AccessoryTags"
        ordering = [ "tag" ]
        verbose_name = "Тег товара"
        verbose_name_plural = "Теги товаров"


class Accessory (models.Model):
    name = models.CharField(
        max_length = 100,
        unique_for_date = "created",
        verbose_name = "Название товара"
    )

    about = models.ForeignKey(
        Game,
        default=None,
        blank=True,
        null=True,
        on_delete=models.CASCADE,
        verbose_name='Для какой игры'
    )

    image = models.FileField(
        default='temp.jpg',
        verbose_name='Изображение'
    )

    content = models.TextField(
        verbose_name = "Полное содержание"
    )

    price = models.IntegerField(
        default = 0,
        verbose_name = "Цена за товар"
    )

    stock = models.IntegerField(
        default = -1, # -1 - unlimited
        verbose_name = "Доступно на заказ"
    )

    virtual = models.BooleanField(
        default = False,
        verbose_name = "Является виртуальным товаром"
    )

    tag = models.ForeignKey(
        AccessoryTag,
        default=None,
        blank=True,
        null=True,
        on_delete=models.SET_NULL,
        verbose_name='Тег'
    )

    created = models.DateTimeField(
        default = datetime.now(),
        db_index = True,
        verbose_name = "Дата создания"
    )
    
    def __str__ (self): return self.name

    class Meta:
        db_table = "Accessories"
        verbose_name = "Товар"
        verbose_name_plural = "Товары"
        ordering = [ "-about" ]


### user ###

class User (AbstractUser):
    photo = models.ImageField(
        default = 'unknown_{rnd}.png'.format(rnd = randint(1, 12)),
        verbose_name = 'Фото профиля',
        upload_to = 'media',
    )

    first = models.CharField(
        max_length = 100,
        verbose_name = "Имя"
    )

    last = models.CharField(
        max_length = 100,
        verbose_name = "Фамилия"
    )

    purchased = models.ManyToManyField(
        Game,
        verbose_name = "Купленные игры",
    )

    purchased_DLCs = models.ManyToManyField(
        DLC,
        verbose_name = "Купленные дополнения",
    )

    is_editor = models.BooleanField(
        default = False,
        verbose_name = "Редактор"
    )
    
    class Meta:
        db_table = "Users"
        ordering = [ "username" ]
        verbose_name = "Пользователь"
        verbose_name_plural = "Пользователи"


class Order (models.Model):
    user = models.ForeignKey(
        User,
        on_delete=models.CASCADE,
        verbose_name='Пользователь'
    )

    games = models.ManyToManyField(
        Game,
        verbose_name = "Заказанные игры",
    )

    dlcs = models.ManyToManyField(
        DLC,
        verbose_name = "Заказанные дополнения",
    )

    accessories = models.ManyToManyField(
        Accessory,
        verbose_name = "Заказанные товары",
    )

    meta = models.TextField(
        default = '',
        verbose_name = "Метаданные заказа"
    )

    status_choices = [
        ('auto-resolve' , 'Куплено'               ),

        ('wait-verified', 'Ожидает проверки'      ),
        ('verified'     , 'Проверено'             ),
        ('paid'         , 'Оплачено'              ),
        ('shipped'      , 'Отгружено'             ),
        ('delivered'    , 'Доставлено'            ),
        ('taken'        , 'Получено'              ),

        ('cancelled'    , 'Отменено пользователем'),
        ('denied'       , 'Отменено продавцом'    ),
        ('returned'     , 'Возвращено'            ),
    ]

    status = models.CharField(
        max_length=20,
        choices = status_choices,
        default = 'wait-verified',
        verbose_name = "Статус заказа"
    )

    comment = models.TextField(
        default = "",
        verbose_name = "Комментарий к статусу заказа"
    )

    address = models.TextField(
        default = "",
        verbose_name = "Адрес доставки"
    )

    created = models.DateTimeField(
        default = datetime.now(),
        db_index = True,
        verbose_name = "Дата поступления заказа"
    )

    class Meta:
        db_table = "Orders"
        ordering = [ "-created" ]
        verbose_name = "Заказ"
        verbose_name_plural = "Заказы"


### blog ###

class ArticleTag (models.Model):
    tag = models.CharField(
        max_length = 20,
        verbose_name = "Тег игры"
    )

    colour = models.CharField(
        max_length = 7,
        verbose_name = "Цвет тега игры"
    )
    
    def __str__ (self): return '#' + self.tag
    
    class Meta:
        db_table = "ArticleTags"
        ordering = [ "tag" ]
        verbose_name = "Тег статьи"
        verbose_name_plural = "Теги статьей"


class Article (models.Model):
    title = models.CharField(
        max_length = 100,
        unique_for_date = "posted",
        verbose_name = "Заголовок"
    )

    image = models.FileField(
        default='temp.jpg',
        verbose_name='Изображение'
    )

    content = models.TextField(
        verbose_name = "Полное содержание"
    )

    posted = models.DateTimeField(
        default = datetime.now(),
        db_index = True,
        verbose_name = "Дата публикации"
    )

    about = models.ForeignKey(
        Game,
        default=None,
        blank=True,
        null=True,
        on_delete=models.CASCADE,
        verbose_name='О какой игре'
    )

    tag = models.ForeignKey(
        ArticleTag,
        default=None,
        blank=True,
        null=True,
        on_delete=models.SET_NULL,
        verbose_name='Тег'
    )

    def __str__ (self): return self.title

    def get_absolute_url (self):
        return reverse("blogpost", args=[str(self.id)])

    class Meta:
        db_table = "Posts"
        ordering = [ "-posted" ]
        verbose_name = "Статья блога"
        verbose_name_plural = "Статьи блога"


class Comment (models.Model):
    text = models.TextField(
        verbose_name='Текст комментария'
    )

    date = models.DateTimeField(
        default=datetime.now(),
        db_index=True,
        verbose_name='Дата комментария'
    )

    author = models.ForeignKey(
        User,
        on_delete=models.CASCADE,
        verbose_name='Автор комментария'
    )

    post = models.ForeignKey(

app/templates/app/pages/intermediate/newpost.html
{% extends "app/layout.html" %}

{% block links %}

{% load staticfiles %}
<link rel="stylesheet" type="text/css" href="{% static 'assets/styles/login.css' %}" />
<link rel="stylesheet" type="text/css" href="{% static 'assets/styles/forms.css' %}" />

{% endblock %}

{% block content %}

<section id="loginForm" class="input_form">
    <form action="." method="POST">
        {% csrf_token %}

        <h4>Новая новость</h4>
        <hr />

        <div class="form-group">
            <label for="id_about">Относится к игре</label>
            <div>
                {{ form.about }}
            </div>
        </div>

        <div class="form-group">
            <label for="id_title">Заголовок</label>
            <div>
                {{ form.title }}
            </div>
        </div>

        <div class="form-group">
            <label for="id_description">Краткое содержание</label>
            <div>
                {{ form.description }}
            </div>
        </div>

        <div class="form-group">
            <label for="id_content">Полное содержание</label>
            <div>
                {{ form.content }}
            </div>
        </div>

        <div class="form-group">
            <label for="id_image">Изображение</label>
            <div>
                {{ form.image }}
            </div>
        </div>

        <div class="form-group">
            <label for="id_extra_tag">Дополнительный тег</label>
            <div>
                {{ form.extra_tag }}
            </div>
        </div>

        <div class="form-group">
            <label for="id_extra_tag_colour">Цвет тега</label>
            <div>
                {{ form.extra_tag_colour }}
            </div>
        </div>

        <div class="form-group">
            <input type="hidden" name="next" value="/" />
            <input type="submit" value="опубликовать" class="click-btn" />
        </div>

        {% if form.errors %}
        <div class="form-group form-warning">
            <svg xmlns="http://www.w3.org/2000/svg" class="inline-svg" viewBox="0 96 960 960"><path d="M479.982 776q14.018 0 23.518-9.482 9.5-9.483 9.5-23.5 0-14.018-9.482-23.518-9.483-9.5-23.5-9.5-14.018 0-23.518 9.482-9.5 9.483-9.5 23.5 0 14.018 9.482 23.518 9.483 9.5 23.5 9.5ZM453 623h60V370h-60v253Zm27.266 353q-82.734 0-155.5-31.5t-127.266-86q-54.5-54.5-86-127.341Q80 658.319 80 575.5q0-82.819 31.5-155.659Q143 347 197.5 293t127.341-85.5Q397.681 176 480.5 176q82.819 0 155.659 31.5Q709 239 763 293t85.5 127Q880 493 880 575.734q0 82.734-31.5 155.5T763 858.316q-54 54.316-127 86Q563 976 480.266 976Zm.234-60Q622 916 721 816.5t99-241Q820 434 721.188 335 622.375 236 480 236q-141 0-240.5 98.812Q140 433.625 140 576q0 141 99.5 240.5t241 99.5Zm-.5-340Z"/></svg>
            <p>пожалуйста, перепроверьте форму</p>
        </div>
        {% endif %}
    </form>
</section>

{% endblock %}


{% block scripts %}

{% load staticfiles %}
<script src="{% static 'app/scripts/jquery.validate.min.js' %}"></script>
<script defer type="application/javascript">
    document.getElementById('id_title'           ).setAttribute('placeholder', 'введите заголовок')
    document.getElementById('id_description'     ).setAttribute('placeholder', 'опишите статью парой предложений')
    document.getElementById('id_content'         ).setAttribute('placeholder', 'весь основной текст - сюда')
    document.getElementById('id_extra_tag'       ).setAttribute('placeholder', 'введите тег')
    document.getElementById('id_extra_tag_colour').setAttribute('placeholder', 'формат #RRGGBB')

    let select = document.getElementById('id_about')
    let option = document.createElement('option')
    option.setAttribute('value', '-1')
    option.setAttribute('selected', 'selected')
    option.innerText = 'Выберите игру'
    select.insertBefore(option, select.firstChild)

    const games = {
        {% for game in game_names %}{{ game.id }}: '{{ game.name }}',{% endfor %}
    }

    for (gid in games) {
        select.querySelector(`option[value='${gid}']`).innerText = games[gid]
    }
</script>

{% endblock %}